# plugin.yml
name: TudySpawners
version: 1.0
main: com.tudy.spawners.TudySpawners
api-version: 1.21
description: Advanced Stack Spawner and Storage Plugin.
website: https://discord.gg/tudy
authors: [Tudy]
depend: [Vault]
commands:
  tudyspawner:
    description: Admin commands
    usage: /tudyspawner reload
permissions:
  tudyspawners.admin:
    description: Grants access to all management commands of the plugin.
    default: op
  tudyspawners.use:
    description: Permission to break and interact with spawners.
    default: true